site_name: T

pages:

- Index: index.md

- Assignment:
    - 2019_0401-0407 4月第一周: assignment/2019-0401-0407.md
    - 2019_0325-0331 3月第四周: assignment/2019-0325-0331.md
    - 2019_0318-0324 3月第三周: assignment/2019-0318-0324.md
    - 2019_0311-0317 3月第二周: assignment/2019-0311-0317.md
    - 2019_0304-0310 3月第一周: assignment/2019-0304-0310.md
    - 2019_0225-0303 2月第五周: assignment/2019-0225-0303.md
    - 2019_0218-0224 2月第四周: assignment/2019-0218-0224.md
    - 2019_0211-0217 2月第三周: assignment/2019-0211-0217.md
    - 2019_0204-0210 2月第二周: assignment/2019-0204-0210.md 
    - 2019_0128-0203 1月第五周: assignment/2019-0128-0203.md
    - 2019_0121-0127 1月第四周: assignment/2019-0121-0127.md
    - 2019_0114-0120 1月第三周: assignment/2019-0114-0120.md
    - 2019_0107-0113 1月第二周: assignment/2019-0107-0113.md
    #- 2018_1224-1230 12月第五周: assignment/2018-1224-1230.md
    #- 2018_1217-1223 12月第四周: assignment/2018-1217-1223.md
    #- 2018_1210-1216 12月第三周: assignment/2018-1210-1216.md
    #- 2018_1022-1028 10月第四周: assignment/2018-1022-1028.md
    #- 2018_1015-1021 10月第三周: assignment/2018-1015-1021.md
    #- 2018_1008-1014 10月第二周: assignment/2018-1008-1014.md
    #- 2018_0924-0930 9月第四周: assignment/2018-0924-0930.md
    #- 2018_0916-0923 9月第三周: assignment/2018-0917-0923.md
    #- 2018_0910-0916 9月第二周: assignment/2018-0910-0916.md
    #- 2018_0903-0909 9月第一周: assignment/2018-0903-0909.md
    #- 2018_0827-0902 8月第五周: assignment/2018-0827-0902.md
    #- 2018_0820-0826 8月第四周: assignment/2018-0820-0826.md
    #- 2018_0813-0819 8月第三周: assignment/2018-0813-0819.md
    #- 2018_0806-0812 8月第二周: assignment/2018-0806-0812.md
    #- 2018_0730-0805 8月第一周: assignment/2018-0730-0805.md
    #- 2018_0723-0729 7月第四周: assignment/2018-0723-0729.md
    #- 2018_0716-0722 7月第三周: assignment/2018-0716-0722.md
    #- 2018_0709-0715 7月第二周: assignment/2018-0709-0715.md
    #- 2018_0702-0708 7月第一周: assignment/2018-0702-0708.md
    #- 2018_0625-0630 6月第四周: assignment/2018-0625-0630.md
    #- 2018_0618-0624 6月第三周: assignment/2018-0618-0624.md
    #- 2018_0611-0615 6月第二周: assignment/2018-0611-0615.md
    #- 2018_0604-0609 6月第一周: assignment/2018-0604-0609.md

- Reading: 
    #- Policy: read/policy.md
    - Sentence: read/sentence.md
    - 26-2 Survival of Plants and Animals in Desert Conditions 沙漠中的动植物的存活: read/26-2.md
    - 29-2 Competition 竞争: read/29-2.md
    - 8-3 Running Water on Mars 火星上流动的水: read/8-3.md
    - 12-3 Water in the Desert 沙漠中的水: read/12-3.md
    - 15-3 Glacier Formation 冰川形成: read/15-3.md
    - 16-3 Planets in Our Solar System 我们太阳系的行星: read/16-3.md
    - 19-3 Discovering the Ice Ages 发现冰河时代: read/19-3.md
    - 20-3 Fossil Preservation: read/20-3.md
    - 21-1 Geothermal Energy: read/21-1.md
    - 34-3 Protection of Plants by Insects: read/34-3.md
    - 34-2 The Development of Steam Power: read/34-2.md
    - 34-1 Islamic Art of the Book: read/34-1.md
    #- 2-3 Early Cinema: read/2-3.md
    #- 3-1 Architecture: read/3-1.md
    #- 3-2 Depletion of the Ogallala Aquifer: read/3-2.md
    #- 3-3 The Long-Term Stability of Ecosystems: read/3-3.md
    #- 4-1 The Cave Art in Europe: read/4-2.md
    #- 4-2 Deer Populations of the Puget Sound: read/4-1.md
    #- 4-3 Petroleum Resources: read/4-3.md
    #- Question: question.md
    #- Simplification: read/simplification.md
    #- Detail: read/detail.md
    #- Negation: read/negation.md
    #- Inference: read/inference.md
    #- Insertion: read/insertion.md
    #- Rhetoric Purpose: read/rhetoricpurpose.md
    #- Article: read/article.md
    
- Writing: 
    #- Policy: write/policy.md
    - Section: write/section.md
    #- Sentence: write/sentence.md
    #- Education: write/education.md
    #- Technology: write/technology.md
    #- Family: write/family.md
    #- Work: write/work.md
    #- Environment: write/environment.md
    #- 32-Integrated: write/32-Integrated.md
    
- Speaking:
    #- Policy: speak/policy.md
    - Task 3: speak/task3.md
    #- Task 4: speak/task4.md
    - Task 5: speak/task5.md        
    - Golden80: speak/golden80.md
    
- Listening:
    - Speak Task 56: listen/speak-task56.md
    #- 老托: listen/old.md
    #- Basics: listen/basics.md
    
- Interview: 
    - 20181216: interview/20181226.md
    - 20180501: interview/20180501.md

- Vocabulary: vocabulary.md
      
#- Tutoring:
    #- 20190219: tutoring/20190219.md
    #- 20190114: tutoring/20190114.md
    #- 20181214: tutoring/20181214.md
    #- Old 93: tutoring/93-en-cn.md

#- Courses:
    #- Reading: courses/reading.md
    #- Speaking: courses/speaking.md
    #- Listening: courses/listening.md
    #- Writing: courses/writing.md
    #- Tutoring: courses/tutoring.md
    
#- Question: question.md

#- Search: read/abc.md

theme:
  name: material
  palette:
    primary: 'Teal'
    accent: 'Purple'

markdown_extensions:
    - admonition
    - codehilite(guess_lang=false,linenums=false)
    - toc(permalink=true)
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde

