theme: material

site_name: T

pages:

- Index: index.md

# - Course: course.md

- Assignment: 
    - 2018_1217-1223 12月第四周: assignment/2018-1217-1223.md
    - 2018_1210-1216 12月第三周: assignment/2018-1210-1216.md
    - 2018_1022-1028 10月第四周: assignment/2018-1022-1028.md
    - 2018_1015-1021 10月第三周: assignment/2018-1015-1021.md
    - 2018_1008-1014 10月第二周: assignment/2018-1008-1014.md
    - 2018_0924-0930 9月第四周: assignment/2018-0924-0930.md
    - 2018_0916-0923 9月第三周: assignment/2018-0917-0923.md
    - 2018_0910-0916 9月第二周: assignment/2018-0910-0916.md
    - 2018_0903-0909 9月第一周: assignment/2018-0903-0909.md
    - 2018_0827-0902 8月第五周: assignment/2018-0827-0902.md
    - 2018_0820-0826 8月第四周: assignment/2018-0820-0826.md
    - 2018_0813-0819 8月第三周: assignment/2018-0813-0819.md
    - 2018_0806-0812 8月第二周: assignment/2018-0806-0812.md
    - 2018_0730-0805 8月第一周: assignment/2018-0730-0805.md
    - 2018_0723-0729 7月第四周: assignment/2018-0723-0729.md
    - 2018_0716-0722 7月第三周: assignment/2018-0716-0722.md
    - 2018_0709-0715 7月第二周: assignment/2018-0709-0715.md
    - 2018_0702-0708 7月第一周: assignment/2018-0702-0708.md
    - 2018_0625-0630 6月第四周: assignment/2018-0625-0630.md
    - 2018_0618-0624 6月第三周: assignment/2018-0618-0624.md
    - 2018_0611-0615 6月第二周: assignment/2018-0611-0615.md
    - 2018_0604-0609 6月第一周: assignment/2018-0604-0609.md

- Read: 
    - Policy: read/policy.md
    - Sentence: read/sentence.md
    - Question: question.md
    - Simplification: read/simplification.md
    - Detail: read/detail.md
    - Negation: read/negation.md
    - Inference: read/inference.md
    - Insertion: read/insertion.md
    - Rhetoric Purpose: read/rhetoricpurpose.md
    - Article: read/article.md
    - 34-1: read/34-1.md
    - 34-2: read/34-2.md
    - 34-3: read/34-3.md
    - 2-3 Early Cinema: read/2-3.md
    - 3-1 Architecture: read/3-1.md
    - 3-2 Depletion of the Ogallala Aquifer: read/3-2.md
    - 3-3 The Long-Term Stability of Ecosystems: read/3-3.md
    - 4-1 The Cave Art in Europe: read/4-2.md
    - 4-2 Deer Populations of the Puget Sound: read/4-1.md
    - 4-3 Petroleum Resources: read/4-3.md
    
- Write: 
    - Policy: write/policy.md
    - Sentence: write/sentence.md
    - Education: write/education.md
    - Technology: write/technology.md
    - Family: write/family.md
    - Work: write/work.md
    - Environment: write/environment.md
    - 32-Integrated: write/32-Integrated.md
    
- Speak:
    - Task 3: speak/task3.md
    - Task 4: speak/task4.md
    - Task 5: speak/task5.md        
    
- Listen:
    - 老托: listen/old.md
    - Basics: listen/basics.md
    
- Tutoring:
    - 20181214: tutoring/20181214.md
    - Old 93: tutoring/93-en-cn.md

- Question: question.md

- Word: word.md

- Search: search.md

# - Word:
#     - 短语: word/phrase.md
#     - Geology: word/geology.md 
#     - Chemistry: word/chemistry.md 
#     - Biology: word/biology.md 
#     - Phychology: word/phychology.md 
#     - Ecology: word/ecology.md 
#     - History: word/history.md 
#     - Art: word/art.md




markdown_extensions:
    - admonition
    - codehilite(guess_lang=false,linenums=false)
    - toc(permalink=true)
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde

extra:
    palette:
    primary: Grey
    accent: Purple
